imgtry4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from myledger import views

urlpatterns = [
    path('',TemplateView.as_view(template_name='general/hpage.html'),name='hpage'),# hpage is the general home page
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth2/login',views.authToChanneli,name='oauth_login'),
    path('oauth2/login/redirect',views.redirector,name='redirect'),
    path('myledger/',include('myledger.urls')),
]

myledger/urls.py
from django.urls import path
from . import views

app_name = 'myledger'
urlpatterns = [
    path('',views.home,name='home'),
    path('dologin',views.dologin,name='dologin'),
    path('dologout',views.dologout,name='dologout'),
    path('dosignup',views.dosignup,name='dosignup'),
    path('userpage/<int:userID>/',views.userpage,name='userpage'),
    path('makegrp/<int:userID>',views.makegrp,name='makegrp'),
    path('userpage/<int:userID>/grpPanel/<int:grpID>/',views.grpPanel,name='grpPanel'),
    path('userpage/<int:userID>/grpPanel/<int:grpID>/userSearch',views.searchUser,name='userSearch'),
    path('userpage/<int:userID>/grpPanel/<int:grpID>/addUser',views.addUser,name='addUser'),
    path('userpage/<int:userID>/grpPanel/<int:grpID>/makeTransaction',views.makeTransaction,name='makeTransaction'),
]

myledger/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class MyGroup(models.Model):
    members = models.ManyToManyField(User, through='Tally')
    groupName = models.CharField(max_length=100, null=True)
    def __str__(self):
        return str(self.groupName)

class Tally(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(MyGroup, on_delete=models.CASCADE, default='')
    balance = models.IntegerField(null=True,default=0)

    class Meta:
        unique_together = [['user','group']]

class Transaction(models.Model):
    group = models.ForeignKey(MyGroup, on_delete=models.CASCADE, default='')
    lender = models.ForeignKey(User,on_delete=models.PROTECT, related_name='lender')
    borrower = models.ForeignKey(User,on_delete=models.PROTECT, related_name='borrower')
    amount = models.PositiveIntegerField()
    lable = models.TextField(max_length=100,null=True)
    transactionDate = models.DateTimeField(auto_now=True)

myledger/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

myledger/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from imgtry4.settings import LOGIN_URL

from myledger.models import MyGroup, Tally, Transaction

# Create your views here.

def home(request):
    return redirect("accounts/login")

# Authentication system:
from django.contrib.auth import authenticate, login, logout

def dologin(request):
    if request.method== 'POST':
        usrname = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=usrname, password=password)
        if user is not None:
            login(request, user)
            theuser = User.objects.get(username=usrname)
            # Redirect to a success page:
            return redirect(reverse('myledger:userpage',kwargs={'userID':theuser.id}))
        else:
            # define an error message:
            err_message='Incorrect username or password'
            # redirect to login page with error message:
            return redirect(reverse('hpage',kwargs={'err_message':err_message}))
    else:
        return redirect(reverse('hpage'))

def dologout(request):
    logout(request)
    # Redirect to a success page:
    return redirect(reverse('hpage'))

from .forms import SignUpForm

def dosignup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse('hpage'))
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
@login_required
def userpage(request,userID):
    theuser = User.objects.get(id=userID)
    hisgroups = theuser.mygroup_set.all()
    # transactions in which user is the lender:
    histransacsl = list(Transaction.objects.filter(lender=theuser))
    # transactions in which user is the borrower:
    histransacsb = list(Transaction.objects.filter(borrower=theuser))
    # combining both lists
    histransacs = histransacsb + histransacsl
    # sorting the list according to transactionDate:
    histransacs.sort(key=lambda x: x.transactionDate)
    # making a dictionary with keys as groups and values as the user's tally for that group:
    grp_dict={}
    i=0
    for agroup in hisgroups:
        grp_dict[agroup]=theuser.tally_set.values('balance')[i]['balance']
        i+=1
    context={'theuser':theuser,'hisgroups':hisgroups,'histransacs':histransacs,'dict':grp_dict}
    return render(request,'myledger/userpage.html',context)

@login_required
def makegrp(request,userID):
    grpName = request.POST.get('groupName')
    grp = MyGroup(groupName=grpName)
    grp.save()
    user = User.objects.get(id=userID)
    grp.members.add(user)
    return grpPanel(request,user.id,grp.id)

@login_required
def grpPanel(request,userID,grpID):
    grp = MyGroup.objects.get(id=grpID)
    theuser = User.objects.get(id=userID)
    hisgroups = theuser.mygroup_set.all()
    grp_dict={}
    i=0
    for agroup in hisgroups:
        grp_dict[agroup]=theuser.tally_set.values('balance')[i]['balance']
        i+=1
    normal_dict = normalized_dict(grp,theuser)
    transacList = Transaction.objects.filter(group=grp)
    context={'theuser':theuser,'hisgroups':hisgroups,'grp':grp,'dict':grp_dict,'normal_dict':normal_dict,'transacList':transacList}
    return render(request,'myledger/grpPanel.html',context)

@login_required
def searchUser(request,userID,grpID):
    grp = MyGroup.objects.get(id=grpID)
    usr = User.objects.get(id=userID)
    qtext= request.GET.get('username')
    suchUsers=User.objects.filter(username__startswith=qtext)
    suchUsers=suchUsers.exclude(username=usr.username)
    context={'suchUsers':suchUsers,'grp':grp,'usr':usr}
    return render(request,'myledger/userList.html',context)

@login_required
def addUser(request,userID,grpID):
    grp= MyGroup.objects.get(id=grpID)
    allusers = User.objects.all()
    for auser in allusers:
        if request.POST.get(str(auser.id))=="clicked":
            grp.members.add(auser)
    grp.save()
    return grpPanel(request,userID,grp.id)

@login_required
def makeTransaction(request,userID,grpID):
    grp= MyGroup.objects.get(id=grpID)
    # person1 is the user:
    person1 = User.objects.get(id=userID)
    # person2 is the other person involved in the transaction:
    person2 = grp.members.get(id=request.POST.get("otherPerson"))
    if person1==person2:
        return grpPanel(request,userID,grp.id)
    amount = int(request.POST.get("amount"))
    # ower tells which person is the lender:
    ower = int(request.POST.get("owedByWho"))
    lable=str(request.POST.get("lable"))
    # tally (object) of person1 with the group grp:
    tally1 = Tally.objects.get(user_id=person1.id,group_id=grp.id)
    # tally (object) of person2 with the group grp:
    tally2 = Tally.objects.get(user_id=person2.id,group_id=grp.id)
    # if ower=1 this means person1 is the lender:
    if ower==1:
        tally1.balance+=amount
        tally2.balance-=amount
        transac = Transaction(group=grp,lender=person1,borrower=person2,amount=amount,lable=lable)
        transac.save()
    # if ower=2 this means person2 is the lender:
    elif ower==2:
        tally1.balance-=amount
        tally2.balance+=amount
        transac = Transaction(group=grp,lender=person2,borrower=person1,amount=amount,lable=lable)
        transac.save()
    tally1.save()
    tally2.save()
    person1.save()
    person2.save()
    grp.save()
    return grpPanel(request,userID,grp.id)

#normalization code 
#it returns a dictionary with keys as user objects in the group grp (except the user usr) and values as the debt/excess of the user usr with other users
#wrote this in one go and now I can't explain what is going on in this :,-( 
def normalized_dict(grp,usr):
    itsMembers = grp.members.all()
    tally_list = []
    i=0
    ans_dict={}
    member_list = list(itsMembers)
    for memberObj in member_list :
        ans_dict[memberObj]=0
    del ans_dict[usr]
    for amember in itsMembers:
        tally_list.append(Tally.objects.get(user_id=amember.id,group_id=grp.id).balance)
        if amember==usr:
            usr_index = i
        i+=1
    temp_dict={index:tally_list[index] for index in range(i)}
    order_list=[]
    sorted_dict = dict(sorted(temp_dict.items(), key=lambda item: item[1], reverse=True))
    order_list=list(sorted_dict.keys())
    usr_order = order_list.index(usr_index)
    l = len(order_list)
    if tally_list[usr_index]<0:
        sum=0
        for t in range(1,l-usr_order):
            sum += tally_list[order_list[l-t]]
        p=0
        while sum<=0:
            sum += tally_list[order_list[p]]
            p+=1
        remainderr = sum
        req_list = order_list[p-1:usr_order]
        usr_money = tally_list[usr_index]
        tally_list[req_list[0]]=remainderr
        q=0
        while usr_money<0:
            temp2=usr_money
            usr_money += tally_list[req_list[q]]
            if usr_money<0:
                ans_dict[member_list[req_list[q]]]=-tally_list[req_list[q]]
            else:
                ans_dict[member_list[req_list[q]]]=temp2
            q+=1

    elif tally_list[usr_index]>0:
        sum=0
        for t in range(0,usr_order):
            sum += tally_list[order_list[t]]
        p=l-1
        while sum>=0:
            sum += tally_list[order_list[p]]
            p-=1
        remainderr=sum
        req_list = order_list[usr_order+1:p+2]
        usr_money = tally_list[usr_index]
        tally_list[req_list[-1]]=remainderr
        q=-1
        while usr_money>0:
            temp2=usr_money
            usr_money += tally_list[req_list[q]]
            if usr_money>0:
                ans_dict[member_list[req_list[q]]]=-tally_list[req_list[q]]
            else:
                ans_dict[member_list[req_list[q]]]=temp2
            q-=1

    return ans_dict

#channel i oauth
# I have registered my app on channel.in but it is not approved till now (March 20, 2022 - 21:45:33). But I will keep this code here (incase app is approved later)
import requests
client_id='Rpd9gbaDjlrLiFcF7yKKsY14f9DUT6OmNhwzFNuJ'
client_secret='g2mqhQDtuGLoAqFmMNs4ebsEWrXMDmvOWWCFg0dee6OB0yVxkAXVf50dOs20ywazwGG8JXaqzQv2O5dbPk17Mjf1kJnPbNRVeRkQFg5Qi0nHvROnKlrUmhbIlt5KWKPJ'
redirect_uri='http://127.0.0.1:8000/oauth2/login/redirect'
auth_url = 'https://channeli.in/oauth/authorise/?client_id='+client_id

def authToChanneli(request):
    return redirect(auth_url)

def redirector(request):
    auth_code = request.GET.get('code')
    final_data = exchanger(auth_code)
    username= final_data.student.enrolmentNumber
    full_name = final_data.person.fullName
    firstName = full_name.split()[0]
    lastName = full_name.split()[-1]
    suchuser = User.objects.filter(username=username)
    if suchuser is not None:
        login(request,suchuser)
        return userpage(request,suchuser.id)
    else:
        suchuser = User.objects.create_user(username=username,first_name=firstName,last_name=lastName)
        login(request,suchuser)
        return userpage(request,suchuser.id)

def exchanger(auth_code):
    final_data={}
    data={
        "client_id":client_id,
        "client_secret":client_secret,
        "grant_type":"authorization_code",
        "code":auth_code,
        "redirect_uri":redirect_uri,
    }
    headers={
        'Content-Type':'application/x-www-form-urlencoded'
    }
    response= requests.post('https://channeli.in/open_auth/token',data=data,headers=headers)
    if response.status_code==200:
        credentials = response.json()
        access_token = credentials['access_token']
        headers={

myledger/templates/myledger/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body style="padding-top:70px; max-width:100%" >
    <nav class="navbar navbar-light bg-light fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Ledger User Page</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">{% block userInfo %}FirstName LastName{% endblock userInfo %}</h5>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'myledger:userpage' theuser.id %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link btn btn-danger" href="{% url 'myledger:dologout' %}">Logout</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    New Group
                  </a>
                  <form method = 'post' class="dropdown-menu p-4" action="{% url 'myledger:makegrp' theuser.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="groupName">Group Name</label>
                      <input type='text' class="form-control" id="groupName" name = 'groupName' placeholder="e.g. Friends' group">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>

      <div class="container mx-2 " style="width:100%;">
          <div class="row">
              <div class="col border border-dark overflow-scroll" style=" max-height:480px" >
                {% block groupList %}
                this area is for the list of groups
                {% endblock groupList %}
              </div>
              <div class="col border border-dark container"  style=" max-height:470px">
                <div class="row row-cols-1">
                  <div class="col overflow-auto border border-dark"  style=" height:235px; width:800px">
                    {% block grpPanel %}This area is for the group view{% endblock grpPanel %}
                  </div>
                  <div class="col overflow-auto border border-dark" style=" height:235px">
                    {% block recentTransactions %}This area is for recent transactions{% endblock recentTransactions %}
                  </div>
                </div>
            </div>
          </div>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
  </body>
</html>

myledger/templates/myledger/grpPanel.html
{% extends 'myledger/base.html' %}
{% block userInfo %}{{theuser.get_full_name}}{% endblock userInfo %}
{% block groupList %}
    {% for hisgroup,hisbalance in dict.items %}
        <li><a href="{% url 'myledger:grpPanel' theuser.id hisgroup.id %}" class="list-group-item list-group-item-action fluid-width:50%">{{ hisgroup.groupName }}
            {% if hisbalance > 0 %}
                <span class="badge rounded-pill bg-success">{{hisbalance}}</span>
            {% elif hisbalance < 0%}
                <span class="badge rounded-pill bg-danger">{{hisbalance}}</span>
            {% else %}
                <span class="badge rounded-pill bg-secondary">{{hisbalance}}</span>
            {% endif %}
            </a></li>
    {%empty%}
        <li>You have no groups! Make one by the menu option in top right</li>
    {% endfor %}
{% endblock groupList %}

{% block grpPanel %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{grp.groupName}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'myledger:userpage' theuser.id %}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Add Member
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="min-width:16rem">
                <li>Search the user to add</li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <form class="d-flex dropdown-item" method='get' action="{% url 'myledger:userSearch' theuser.id grp.id%}" >
                    <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name='username'>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form>
                </li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Add Transaction
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="min-width:80rem">
                <li>add details of Transaction</li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <form class="d-flex dropdown-item" method='post' action="{% url 'myledger:makeTransaction' theuser.id grp.id%}">
                    {% csrf_token %}
                    <input class="form-control" type="text" value="I" aria-label="readonly input example" readonly>
                    <div class="input-group mb-3" >
                      <select class="form-select" id="inputGroupSelect01" name="owedByWho" required>
                        <option selected>Choose...</option>
                        <option value="1">gave</option>
                        <option value="2">took from</option>
                      </select>
                    </div>
                    <div class="input-group mb-3">
                      <select class="form-select" id="inputGroupSelect01" name="otherPerson" required>
                        {% for member in normal_dict.keys %}
                        <option value="{{member.id}}">{{member}}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="input-group mb-3">
                      <label for="amount">Amount in Rupees:</label>
                      <input type="number" id="amount" name="amount" min="1" required> 
                    </div>
                    <input class="form-control" type="text" placeholder="Add label" name="lable" aria-label="input">
                    <button class="btn btn-outline-success" type="submit">Done</button>
                  </form>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <h3>Your Tally</h3>
    {% for member,histally in normal_dict.items %}
    <li>{{member}}
      {% if histally > 0 %}
      <span class="badge rounded-pill bg-success">{{histally}}</span>
      {% elif histally < 0%}
      <span class="badge rounded-pill bg-danger">{{histally}}</span>
      {% else %}
      <span class="badge rounded-pill bg-secondary">{{histally}}</span>
      {% endif %}
    </li>
    {% endfor %}
    
    {% endblock grpPanel %}
    {% block recentTransactions %}
    <h3>This group's Transactions</h3>
    {% for transac in transacList %}
        {% if transac.lender == theuser %}
            <li><i>{{transac.transactionDate}}</i>  You gave Rs {{transac.amount}} to {{transac.borrower}} ({{transac.lable}})</li>
        {% elif transac.borrower == theuser %}
            <li><i>{{transac.transactionDate}}</i>  {{transac.lender}} gave Rs {{transac.amount}} to You ({{transac.lable}})</li>
        {% else %}
            <li><i>{{transac.transactionDate}}</i>  {{transac.lender}} gave Rs {{transac.amount}} to {{transac.borrower}} ({{transac.lable}})</li>
        {% endif %}
    {% endfor %}
    {% endblock recentTransactions %}

myledger/templates/myledger/userList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>User List</title>
</head>
<body>
    <h3>Check users to add to {{grp.groupName}}
    <form method="post" action="{% url 'myledger:addUser' usr.id grp.id %}">
        {% csrf_token %}
    {% for auser in suchUsers %}<div class="list-group">
        <label class="list-group-item">
          <input class="form-check-input me-1" type="checkbox" value="clicked" name="{{auser.id}}">
          {{auser.username}} ({{auser.first_name}} {{auser.last_name}})
        </label>
        
    {% endfor %}
    <input class="btn btn-success" type="submit" value="Add">
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

myledger/templates/myledger/userpage.html
{% extends 'myledger/base.html' %}
{% block userInfo %}{{theuser.get_full_name}}{% endblock userInfo %}
{% block groupList %}
    {% for hisgroup,hisbalance in dict.items %}
        <li><a href="{% url 'myledger:grpPanel' theuser.id hisgroup.id %}" class="list-group-item list-group-item-action fluid-width:50%">{{ hisgroup.groupName }}
            {% if hisbalance > 0 %}
                <span class="badge rounded-pill bg-success">{{hisbalance}}</span>
            {% elif hisbalance < 0%}
                <span class="badge rounded-pill bg-danger">{{hisbalance}}</span>
            {% else %}
                <span class="badge rounded-pill bg-secondary">{{hisbalance}}</span>
            {% endif %}
            </a></li>
    {%empty%}
        <li>You have no groups! Make one by the menu option in top right</li>
    {% endfor %}
{% endblock groupList %}
{% block grpPanel %}
Select a group to view its details
{% endblock grpPanel %}
{% block recentTransactions %}
<h3>Your transactions</h3>
{% for transac in histransacs %}
{% if transac.lender == theuser%}
<li><i>{{transac.transactionDate}}</i>  <b>{{transac.group}} :</b> You gave Rs {{transac.amount}} to {{transac.borrower}} ({{transac.lable}})</li>
{% else %}
<li><i>{{transac.transactionDate}}</i>  <b>{{transac.group}} :</b> {{transac.lender}} gave Rs {{transac.amount}} to You ({{transac.lable}})</li>
{% endif %}
{% endfor %}
{% endblock recentTransactions %}